# Generated by Django 3.2.3 on 2021-06-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('datetime_id', models.IntegerField()),
                ('datetime_start', models.DateTimeField()),
                ('datetime_end', models.DateTimeField()),
                ('submit_datetime', models.DateTimeField()),
                ('is_main_order', models.IntegerField(default=1)),
                ('main_order_id', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=1)),
                ('processed_datetime', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'BookingRecord',
            },
        ),
        migrations.CreateModel(
            name='EveryDayBookingInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime_start', models.DateTimeField()),
                ('datetime_end', models.DateTimeField()),
                ('maximum_number', models.IntegerField(default=0)),
                ('remain_number', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'EveryDayBookingInfo',
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('configuration_name', models.CharField(max_length=50)),
                ('configuration_value', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'SystemConfiguration',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('id_card', models.CharField(max_length=50)),
                ('identity_authentication_type', models.IntegerField(default=0)),
                ('wechat_open_id', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('user_role', models.IntegerField(default=1)),
                ('createTime', models.DateTimeField()),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
