# Generated by Django 3.2.3 on 2021-06-08 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminWeb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='createTime',
        ),
    ]
